### ISSUE TITLE
Allow Users to specify retention windows for JoinWithExpiration in SQL

### ISSUE THREAD

**Issue by jacksonrnewhouse** [ArroyoSystems/arroyo#117]
Currently non-windowed joins in SQL always have a retention of 24 hours. This can be both much too long and much too short, depending on the use case. Flink currently handles this with a configurable execution option, [table.exec.state.ttl](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/config/#table-exec-state-ttl). We could follow suit by allowing settings to be passed into the GrpcApi, or figure out a way to have it specified within the body of the query.

**Comment by mwylde** [comment]
This was fixed with https://github.com/ArroyoSystems/arroyo/pull/741
