### ISSUE TITLE
Add support for NATS as a connector

### ISSUE THREAD

**Issue by bruth** [ArroyoSystems/arroyo#162]
Hi there 👋 ! I saw in the docs to open an issue to propose new connectors. Have you heard of NATS.io (https://github.com/nats-io/nats-server) by chance? It would be a great addition to the set of connectors. What is the process for contributing one? Thanks!

**Comment by jacksonrnewhouse** [comment]
Hi @bruth! Thanks for raising this. It's currently a giant pain to add new connections, as you can see in #106. @mwylde is working on a new way of managing connections and their accompanying sources and sinks. This should make it easier to add new connectors such as NATS. Fortunately it looks like there are already Rust bindings for NATS at https://docs.rs/nats/latest/nats/asynk/index.html.

**Comment by bruth** [comment]
Understood, thanks for the response! When the new method is ready, let me know.

**Comment by arnarg** [comment]
@jacksonrnewhouse In the release notes for [v0.4.0](https://github.com/ArroyoSystems/arroyo/releases/tag/v0.4.0) it's mentioned that there is now a standardized trait for connectors. Does this mean that work on a NATS connector can start?

**Comment by mwylde** [comment]
Hi @arnarg yes, at this point implementing a nats connector should be pretty straightforward. You can take for example this PR that adds a connector for Fluvio: https://github.com/ArroyoSystems/arroyo/pull/195

**Comment by AbstractiveNord** [comment]
Up.

**Comment by markfarnan** [comment]
Up and Following

A NATS Jetstream connector would be very usefull here.

**Comment by mwylde** [comment]
Closed with #578

**Comment by AbstractiveNord** [comment]
NATS Jetstream is not available as sink.
