### ISSUE TITLE
Missing 'schemaType' field in schema registry response

### ISSUE THREAD

**Issue by taylorsmithgg** [ArroyoSystems/arroyo#172]
Arroyo version 0.3.0

Using confluent schema registry during kafka source setup, this is the only response I am able to retrieve:
```
Missing 'schemaType' field in schema registry response
```

My set up is standard debezium + postgres w/confluent schema registry v6.1.0 using avro, self-hosted.

**Comment by jacksonrnewhouse** [comment]
Hi Taylor, that error is originating [here](https://github.com/ArroyoSystems/arroyo/blob/master/arroyo-api/src/sources.rs#L969). In particular, the API response is being successfully parsed but is missing the `schemaType` field. It might be helpful for debugging to print the whole response out in the error message.

I do want to note that we have yet to add AVRO support, so once you resolve this that will become your next hurdle.

Cheers!

**Comment by taylorsmithgg** [comment]
@jacksonrnewhouse Unfortunately w/debezium and schema registry that's somewhat of a hard requirement.
Is there a roadmap for AVRO support? I'd love to check it out once it's supported.

**Comment by mwylde** [comment]
@taylorsmithgg Avro support is now available in #422, including comprehensive support for schema registry
