### ISSUE TITLE
Change the image tag to tip in the Helm values (defaults)

### ISSUE THREAD

**Issue by haoxins** [ArroyoSystems/arroyo#180]
Just like what https://github.com/apache/flink-kubernetes-operator/blob/main/helm/flink-kubernetes-operator/values.yaml#L28 does.

Can we change the default image tag in the Helm values to `tip`?
If the end users want to specify the version, they should override the field and defaults to tip (latest) for others.

cc @jacksonrnewhouse

**Comment by edmondop** [comment]
@haoxins will take care of this after we merge #271

**Comment by haoxins** [comment]
thanks

**Comment by edmondop** [comment]
I think it's good to leave it open until PR are merged
