### ISSUE TITLE
Implement date_trunc(), date_part(), and extract()

### ISSUE THREAD

**Issue by jacksonrnewhouse** [ArroyoSystems/arroyo#28]
The input will be a possibly optional SystemTime, as that is the representation for timestamps currently. Follow the documentation from data fusion for [date_trunc](https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html#date-trunc), [date_part](https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html#date-part), and [extract](https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html#extract).

The most natural place is a new variant on Expression for DateFunction(), with a corresponding DateExpression. Testing should be done by adding additional assertions to arroyo-sql-testing.

**Comment by AK-ayush** [comment]
Hi @jacksonrnewhouse, I'd like to work on this and #25 if that's okay with you?

**Comment by jacksonrnewhouse** [comment]
@AK-ayush, that'd be great. If you have any trouble getting your dev environment setup or figuring out some of the moving parts of arroyo-sql, feel free to reach out in the Discord.

**Comment by kamalesh0406** [comment]
Hello, I can also help out with this issue. @AK-ayush would you be willing to split the implementation of each function between us? I have the bandwidth to implement `date_part`. Thanks!!

**Comment by AK-ayush** [comment]
Sure @kamalesh0406, please go ahead.

**Comment by edmondop** [comment]
Can I move forward with this? It sees there is no pr open

**Comment by kamalesh0406** [comment]
@edmondop Sure you can look into it. I was only able to partially complete it and I don't think so I have the time to work on it right now :) .

**Comment by jacksonrnewhouse** [comment]
Handled by #181.
