### ISSUE TITLE
Implement DataFusion Hashing Functions

### ISSUE THREAD

**Issue by jacksonrnewhouse** [ArroyoSystems/arroyo#30]
DataFusion [supports](https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html#hashing-functions) md5, sha224, sha256, sha384, sha512.

**Comment by alex-astronomer** [comment]
I have been working on this.

**Comment by akennedy4155** [comment]
Completed, but no permissions to push branch.  Are there any other contributors or a process for that yet, besides just the founders?

**Comment by jacksonrnewhouse** [comment]
You should be able to open a PR, which will get reviewed and merged. That's what we did with Tyler's changes, https://github.com/ArroyoSystems/arroyo/pull/8.
