### ISSUE TITLE
AWS region for Kinesis

### ISSUE THREAD

**Issue by MarcoLugo** [ArroyoSystems/arroyo#307]
I was using the Kinesis source earlier within Kubernetes and had an issue with the region. This can probably be worked around with an environment variable but maybe AWS region should be a Kinesis parameter?

Thanks

<img width="996" alt="image" src="https://github.com/ArroyoSystems/arroyo/assets/6843447/bffb1ec0-918c-42ab-a000-7f02efc9f156">

**Comment by mwylde** [comment]
Fixed in #313
