### ISSUE TITLE
Add Discussion to GH

### ISSUE THREAD

**Issue by alex-astronomer** [ArroyoSystems/arroyo#35]
I'd like to see a GH discussion section for questions for users and devs that aren't necessarily issues, bugs, or feature requests.  Would this be possible with the Apache license now?

**Comment by wardnath** [comment]
+1 ; I would like to be able to keep tabs on discussion re: feature releases. Particularly K8s integration

**Comment by jacksonrnewhouse** [comment]
Opened up! Excited to get discussing!
