### ISSUE TITLE
Developer Setup Changes Needed - Typo and other commands

### ISSUE THREAD

**Issue by akennedy4155** [ArroyoSystems/arroyo#39]
https://doc.arroyo.dev/developing/dev-setup

---

> We use pnpm and vite for *frotend* development.

Should be frontend.

---

I had to run `pnpm install` before building.

```
$ cd arroyo-console
$ pnpm install
$ pnpm build
```

---

Instructions on front end console states:

![image](https://user-images.githubusercontent.com/12237683/231893630-3dbc2cae-7009-4ba6-9a59-cc61ee13598f.png)

However, I had to run `pnpm run dev` to start the local console.

**Comment by akennedy4155** [comment]
> > (note the api must also be running locally for this to be functional).
> 
> I ran the api in a separate process with `cargo run` in the `arroyo-api` directory. Is this the correct way to run this? Can we add that to the developer setup instructions as well?

Found this in the Getting Started guide 
![image](https://user-images.githubusercontent.com/12237683/231895252-3c37731f-052a-4801-a5a3-3e5a15ed7153.png)

Maybe we could link this to the dev setup somehow?

**Comment by mwylde** [comment]
Thanks for the feedback! I've opened a PR to fix these issues in our docs repo: https://github.com/ArroyoSystems/arroyo-docs/pull/6.
