### ISSUE TITLE
More clearly document a "long time" with regards to compiling pipelines

### ISSUE THREAD

**Issue by akennedy4155** [ArroyoSystems/arroyo#40]
With a basic developer setup and the simple tutorial pipeline, compiling is taking longer than 30 minutes.

I am seeing this repeated in the `api` logs when on the main page for the pipeline:

```
2023-04-13T22:26:11.887964Z ERROR response failed{code="Internal" path="/arroyo_api.ApiGrpc/GetJobMetrics"}: arroyo_server_common: new
...
2023-04-13T22:26:42.494625Z ERROR response failed{code="Internal" path="/arroyo_api.ApiGrpc/GetJobMetrics"}: arroyo_server_common: new
```

### Postgres

Running via `postgres -D /usr/local/var/postgres`

I made sure to do the setup with the arroyo database, the correct arroyo user/pass and ran the migrations.

### API

```
cd arroryo/arroyo-api
cargo run
```

### Controller

```
cd arroyo/arroyo-controller
cargo run
```

### Console

```
pnpm run dev
```

All in separate panes in iterm mux

---

I'm going to let it run for an hour or so and check to see if it's made any progress.

Not seeing any logs that incidicate such, the logs that I see on the `api` were added above, and here's what I'm seeing on the controller:

```
2023-04-13T22:20:54.478312Z  INFO arroyo_controller: Using process scheduler
2023-04-13T22:20:54.486223Z  INFO arroyo_controller: Starting arroyo-controller on 0.0.0.0:9190
2023-04-13T22:20:54.486307Z  INFO arroyo_server_common: Starting arroyo-controller admin server on 0.0.0.0:9191
2023-04-13T22:20:54.507758Z  INFO arroyo_controller::states: starting state machine job_id="hbmgfamd"
2023-04-13T22:20:54.509053Z  INFO arroyo_controller::states: state transition job_id="hbmgfamd" from="Created" to="Compiling"
2023-04-13T22:20:54.516598Z  INFO arroyo_controller::states::compiling: Compiling pipeline job_id="hbmgfamd" hash="f9ubevthoxw2g6c7"
2023-04-13T22:20:54.517804Z  INFO arroyo_controller::compiler: digraph {
    0 [ label = "source_0:UnboundedNexmarkSource<qps: 100>" ]
    1 [ label = "watermark_1:Watermark" ]
    2 [ label = "sink_4:NullSink" ]
    3 [ label = "map_2:expression<fused<map,filter>:OptionalRecord>" ]
    0 -> 1 [ label = "() → arroyo_types::nexmark::Event" ]
    3 -> 2 [ label = "() → generated_struct_16429945049069439673" ]
    1 -> 3 [ label = "() → arroyo_types::nexmark::Event" ]
}
2023-04-13T22:23:43.822146Z  INFO arroyo_controller::states: starting state machine job_id="dtendbjv"
2023-04-13T22:23:43.823730Z  INFO arroyo_controller::states: state transition job_id="dtendbjv" from="Created" to="Compiling"
2023-04-13T22:23:43.832809Z  INFO arroyo_controller::states::compiling: Compiling pipeline job_id="dtendbjv" hash="kbnrqmwueowoiayb"
2023-04-13T22:23:43.834899Z  INFO arroyo_controller::compiler: digraph {
    0 [ label = "source_0:UnboundedNexmarkSource<qps: 100>" ]
    1 [ label = "watermark_1:Watermark" ]
    2 [ label = "sink_10:NullSink" ]
    3 [ label = "map_2:expression<fused<map,aggregator_key>:Record>" ]
    4 [ label = "aggregate_window_4:SlidingWindowAggregator<SlidingWindow(size: 1m, slide: 5s)>" ]
    5 [ label = "aggregation_8:expression<fused<aggregation,map>:Record>" ]
    6 [ label = "aggregation_5:expression<fused<aggregation,aggregator_key>:Record>" ]
    7 [ label = "aggregate_window_7:TumblingWindowAggregator<TumblingWindow(0ms)>" ]
    0 -> 1 [ label = "() → arroyo_types::nexmark::Event" ]
    7 -> 5 [ label = "generated_struct_7077236267445092260 → generated_struct_11296174908488371850" ]
    1 -> 3 [ label = "() → arroyo_types::nexmark::Event" ]
    3 -> 4 [ label = "generated_struct_2862623353463512223 ⤨ generated_struct_16429945049069439673" ]
    5 -> 2 [ label = "() → generated_struct_8568894031591935709" ]
    4 -> 6 [ label = "generated_struct_2862623353463512223 → generated_struct_8556445246977061536" ]
    6 -> 7 [ label = "generated_struct_7077236267445092260 ⤨ generated_struct_8241898945625653774" ]
}
```

The two pipelines that I'm trying to compile are:

```
SELECT count(distinct bid.price) AS count,
        hop(interval '5 seconds', interval '60 seconds') AS window
            FROM nexmark 
            GROUP BY window;
```

AND

```
select bid from nexmark where bid is not null;
```

**Comment by akennedy4155** [comment]
Also should note I started the `api` first, and then the `controller`.  I restarted both to test, and started them in the order of `controller` and then `api`.  Once I did that, the errors on the `api` went away.

The `controller` also picked up the compile when it started again (was thrilled to see that the controller recognizes that the compile operation wasn't complete!).  FSM magic?

**Comment by jacksonrnewhouse** [comment]
This looks like things are generally working. I'd run top and see if you see cargo/rust things using a fair amount of CPU. I generally start the services like `cargo run  --bin arroyo-api` `cargo run  --bin arroyo-controller`. Yeah, the controller marches through the state machine and they can be started in any order. If the API is down then the frontend won't be able to do anything, if the controller is down then jobs will sit in the "Created" state.

**Comment by akennedy4155** [comment]
Forgot to add.... I went to my activity monitor and saw that the controller and api processes are only taking like 0.2% CPU, however I'm seeing a few `rustc` processes that are consuming a bunch of cores:

![image](https://user-images.githubusercontent.com/12237683/231898290-01f295a5-f957-44f1-9e72-715568005567.png)

So I think that's a good sign.  In any case, we might want to add some sort of order of magnitude to the "long time" that compiles can take for the first time, should this work after an hour or so that I'm gonna let it sit.

---

> Note that the first query may take some time to compile, although subsequent queries should be much faster.

->

> Note that the first query may take *up to X minutes/hours* to compile, although subsequent queries should be much faster.

**Comment by akennedy4155** [comment]
Annnnnnnd it's working!  Patience pays off.  I'll leave this open while we decide what to do about adding ~20-30 min or whatever we see fit to the docs just to let people know that it *is* actually doing something.

Also, having some sort of "compile in progress" msg on the controller periodically would be nice just to know that it's still processing.
