### ISSUE TITLE
Improve Type Checking of SQL types in planning

### ISSUE THREAD

**Issue by jacksonrnewhouse** [ArroyoSystems/arroyo#446]
#439 raised the issue of subtraction producing incorrect generated code, leading to a compile time failure. This is partially addressed in #441, which will return a planning error if a projection calculation returns an unsupported type, including a Duration. However, there are still issues if there are problematic expressions nested within calculations. For instance, the following query plans successfully but produces the same compilation error:
 
 ```
 select CAST(bid.datetime - DATE '2023-12-03' as string)
from nexmark
group by 1;
```

**Comment by mwylde** [comment]
This is fixed in 0.10.
