### ISSUE TITLE
why in tumbling_local_aggregator module, rx not equal to tx?

### ISSUE THREAD

**Issue by javacoderxxp** [ArroyoSystems/arroyo#449]
In First pipeline case, why tumbling_local_aggregator_6 module events rx = 92eps, but tx = 32eps?
When I copy the pipeline, make nexmark source as 10000/s, tumbling_local_aggregator_6 module events rx = 9242eps, but tx = 641eps?
<img width="1345" alt="image" src="https://github.com/ArroyoSystems/arroyo/assets/17718166/e7a7a60b-50fa-4a3a-a90c-1f72def2abec">
<img width="727" alt="image" src="https://github.com/ArroyoSystems/arroyo/assets/17718166/448c56f9-23f8-4d99-a12f-f64a4b64b8a0">

**Comment by jacksonrnewhouse** [comment]
Hi there! Thanks for the question. What's happening is that the tumbling local aggregator does some partial aggregation before sending data onto the downstream node. As that edge is a shuffle, it will, in general, cross a network boundary, requiring serialization and deserialization. This is similar to the combiner that you see in some map-reduce systems, including [Hadoop](https://hadoop.apache.org/docs/stable/hadoop-mapreduce-client/hadoop-mapreduce-client-core/MapReduceTutorial.html#:~:text=Users%20can%20optionally%20specify%20a%20combiner%2C%20via%20Job.setCombinerClass(Class)%2C%20to%20perform%20local%20aggregation%20of%20the%20intermediate%20outputs%2C%20which%20helps%20to%20cut%20down%20the%20amount%20of%20data%20transferred%20from%20the%20Mapper%20to%20the%20Reducer.).

Hope this answers your question!

**Comment by javacoderxxp** [comment]
> Hi there! Thanks for the question. What's happening is that the tumbling local aggregator does some partial aggregation before sending data onto the downstream node. As that edge is a shuffle, it will, in general, cross a network boundary, requiring serialization and deserialization. This is similar to the combiner that you see in some map-reduce systems, including [Hadoop](https://hadoop.apache.org/docs/stable/hadoop-mapreduce-client/hadoop-mapreduce-client-core/MapReduceTutorial.html#:~:text=Users%20can%20optionally%20specify%20a%20combiner%2C%20via%20Job.setCombinerClass(Class)%2C%20to%20perform%20local%20aggregation%20of%20the%20intermediate%20outputs%2C%20which%20helps%20to%20cut%20down%20the%20amount%20of%20data%20transferred%20from%20the%20Mapper%20to%20the%20Reducer.).
> 
> Hope this answers your question!

Thank u.
