### ISSUE TITLE
The current udf data exchange uses WASM by gRPC, which has a lot of overhead, have you considered using hot load technology?

### ISSUE THREAD

**Issue by Doslin** [ArroyoSystems/arroyo#536]
ref: [hot-lib-reloader-rs](https://github.com/rksm/hot-lib-reloader-rs) [rust_libloading](https://github.com/nagisa/rust_libloading)

**Comment by mwylde** [comment]
Thanks for your question! To clarify, we don't use gRPC for UDF communication. gRPC is used for control plane RPCs, but is never used in the data plane. UDFs are directly compiled into the pipeline binary, so there is no overhead there.
