### ISSUE TITLE
The barriers to getting started with rust are too high. Has UDF considered using a language with a lower learning curve like Python or Golang?

### ISSUE THREAD

**Issue by Doslin** [ArroyoSystems/arroyo#537]

**Comment by mwylde** [comment]
Hey @Doslin — thanks for contributing! Questions like this are a better fit for our [Github discussion forum](https://github.com/ArroyoSystems/arroyo/discussions) or [discord](https://discord.com/invite/cjCr5rVmyR). If you'd like to make a feature request for Python or Golang UDFs, that could also be a good issue to file.
