### ISSUE TITLE
Maintenance for long running clusters

### ISSUE THREAD

**Issue by harshit2283** [ArroyoSystems/arroyo#562]
Currently Arroyo stores all metadata for checkpoints in `checkpoints` table, overtime it grows upto a significant size which may impact performance.

![Screenshot 2024-03-11 at 15 29 51](https://github.com/ArroyoSystems/arroyo/assets/20598166/fd695175-358b-41b8-9e5e-8b855c391e05)

Immediate solve (by @mwylde ) is to run this query manually ->
```
DELETE FROM checkpoints
WHERE checkpoints.id != (
  SELECT id FROM checkpoints
  WHERE job_id = '{{ JOB_ID }}'
  ORDER BY finish_time DESC
  LIMIT 1
) AND job_id='{{ JOB_ID }}';
```

**Comment by jacksonrnewhouse** [comment]
Just merged the fix
