### ISSUE TITLE
Change checkpoint interval dynamically

### ISSUE THREAD

**Issue by benjaminawd-flowdesk** [ArroyoSystems/arroyo#629]
Currently, the only way to set a checkpoint interval is by passing in the `checkpointIntervalMicros` argument via the Arroyo API either when [creating](https://doc.arroyo.dev/api-reference/pipelines/create-a-new-pipeline) or [updating](https://discord.com/channels/1092704334808092754/1092964011756228628/1242149659418296520) the pipeline. However, when updating the pipeline, the pipeline doesn't dynamically update and only takes effect after a pipeline is stopped/started.

It would be nice to dynamically update the pipeline, so that the pipeline doesn't need to be stopped and started in order for the changes to occur.

(raised from [Discord](https://discord.com/channels/1092704334808092754/1092964011756228628/1242149659418296520))

**Comment by mwylde** [comment]
Addressed in #636
