### ISSUE TITLE
Arroyo should use a single image in helm

### ISSUE THREAD

**Issue by chokosabe** [ArroyoSystems/arroyo#651]
Arroyo installed via helm pulls the image twice. Once for the controller and again for the worker. Further to this, the worker image pull doesn't use the imagepullsecrets, making the setup useless and potentially confusing.

Makes more sense to have a single image with a single defined set of imagepullsecrets

**Comment by chokosabe** [comment]
Quickest fix for this is just to get the worker image pull using the defined imagepullsecrets as well.

**Comment by mwylde** [comment]
Fixed in #669
