### ISSUE TITLE
Helm chart has misconfigured service ports

### ISSUE THREAD

**Issue by yonryzhu** [ArroyoSystems/arroyo#682]
The Service defined by the Helm chart has hardcoded [targetPorts](https://github.com/ArroyoSystems/arroyo/blob/42c480c4c6d2895615de1a64a411326cdfc54efd/k8s/arroyo/templates/controller.yaml#L152) but configurable pod [containerPorts](https://github.com/ArroyoSystems/arroyo/blob/42c480c4c6d2895615de1a64a411326cdfc54efd/k8s/arroyo/templates/controller.yaml#L101). This only works with the default chart values and breaks if any other ports are configured.

I recommend setting the [targetPort](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec) to the name of the containerPort.

**Comment by mwylde** [comment]
Thanks for reporting this issue, this should be fixed with #690 and helm chart version 0.11.2.
