### ISSUE TITLE
Memory usage slowly climbs up (suspected memory leak)

### ISSUE THREAD

**Issue by hazelnut-99** [ArroyoSystems/arroyo#691]
After launching a pipeline, the worker pod's memory usage slowly increases
<img width="700" alt="image" src="https://github.com/user-attachments/assets/d0f3892c-81d8-41cb-8d2c-bfbebe221ac4">
below is corresponding cpu usage
<img width="706" alt="image" src="https://github.com/user-attachments/assets/55ac06d8-3ca0-4448-85ae-6daa498716e5">

This pipeline uses kafka source and kafka sink. During some time intervals, the source kafka topic has no traffic, aligning with the low cpu usage periods. However, the memory usage slowly increases monotonically. 

Could it be a memory leak issue? 

Version: ```ghcr.io/arroyosystems/arroyo:tip``` 
Configuration & environment:  kubernetes scheduler, a distributed kubernetes cluster
Query
```
CREATE TABLE my_kafka_sink (
    field_1 TEXT,
    field_2 TEXT,
    field_3 DOUBLE,
    ts_1 BIGINT,
    ts_2 BIGINT
) WITH (
    'connector' = 'kafka',
    'avro.confluent_schema_registry' = 'true',
    'bootstrap_servers' = 'my_servers',
    'schema_registry.endpoint' = 'my_endpoint',
    'type' = 'sink',
    'topic' = 'my_topic',
    'format' = 'avro'
);

INSERT INTO my_kafka_sink 
select table_1.field_1, table_1.field_2, 
    (table_2.field_y - table_1.field_z) as field_3,
    table_1.ts as ts_1, table_2.ts as ts_2
from
(
    select field_1, field_2, hop(INTERVAL '5' second, INTERVAL '3' minute) as window, 
    last_value(field_z) as field_z, last_value("timestampMillis") as ts
    from connection_1
    group by 1, 2, 3
) as table_1 join 
(
    select field_1, field_2, hop(INTERVAL '5' second, INTERVAL '3' minute) as window, 
    last_value(value_latest) as field_y, last_value("timestampMillis") as ts
    from connection_2
    group by 1, 2, 3
) as table_2
on table_1.field_1 = table_2.field_1 and 
    table_1.field_2 = table_2.field_2 and 
    table_1.window = table_2.window
```

**Comment by hazelnut-99** [comment]
mostly inactive_anon, below is the memory.stat under cgroup
```
cache 1368399872
rss 421425152
rss_huge 392167424
shmem 1367359488
mapped_file 458752
dirty 0
writeback 0
swap 0
pgpgin 488883
pgpgout 149882
pgfault 105704
pgmajfault 8
inactive_anon 1793511424
active_anon 20480
inactive_file 954368
active_file 86016
unevictable 0
hierarchical_memory_limit 8589934592
hierarchical_memsw_limit 8589934592
total_cache 1368399872
total_rss 421425152
total_rss_huge 392167424
total_shmem 1367359488
total_mapped_file 458752
total_dirty 0
total_writeback 0
total_swap 0
total_pgpgin 488883
total_pgpgout 149882
total_pgfault 105704
total_pgmajfault 8
total_inactive_anon 1793511424
total_active_anon 20480
total_inactive_file 954368
total_active_file 86016
total_unevictable 0
```

**Comment by hazelnut-99** [comment]
Controller's memory usage slowly climbs up as well.
<img width="1654" alt="image" src="https://github.com/user-attachments/assets/dfaad165-82d7-4022-9b97-09300100cc19">

**Comment by mrchypark** [comment]
any update here? I have same issue.

**Comment by mwylde** [comment]
Thanks for the reports, we're investigating.

**Comment by mwylde** [comment]
We've merged a fix for a memory leak in the worker with certain queries with #717. Still looking into issues in the controller but nothing definitive there.

**Comment by mwylde** [comment]
This appears to be fixed, but please re-open if you continue to see a problem with memory growth. We've also added some helpful memory profiling tools which can help debug.
