### ISSUE TITLE
For API, some functions use `Transaction` while others use `impl GenericClient` 

### ISSUE THREAD

**Issue by alex-astronomer** [ArroyoSystems/arroyo#70]
I think that the `impl GenericClient` argument to these functions makes more sense to allow them to use either `Transaction` or a generic Postgres client.

Would it make sense to refactor all of the functions such as `create_connection`, `delete_source`, `get_pipelines` etc. to all use `GenericClient` instead of a concrete type such as `Transaction`?

**Comment by mwylde** [comment]
Unfortunately, Transaction and GenericClient are not interchangeble. In some contexts we need to be able to operate within an existing transaction, which is why those methods take Transaction.
