### ISSUE TITLE
Potentially wrong documentation

### ISSUE THREAD

**Issue by placintaalexandru** [ArroyoSystems/arroyo#796]
In the documentation from [here](https://doc.arroyo.dev/configuration#environment-variables), it is mentioned that env variables are prefixed with `ARROYO__ `, but the last example mentions:
```
api.bind-address => API__BIND_ADDRESS
```

Shouldn't the documentation mention `ARROYO__API__BIND_ADDRESS` ?

Which env var is arroyo app using?

**Comment by mwylde** [comment]
Thanks for reporting, fixed in https://github.com/ArroyoSystems/arroyo-docs/commit/3dcb702329f930659b90a6a952a714d83170ba34
