### ISSUE TITLE
S3 sink pipeline fails in between and is never able to restart in v0.12.0

### ISSUE THREAD

**Issue by prakkashm** [ArroyoSystems/arroyo#802]
We are testing arroyo v0.12.0 before upgrading our current version v0.10.1. It's on a K8s setup.
During this testing, I ran a kafka to s3 pipeline using arroyo SQL (`rollover_seconds` is 1 hour and checkpoint interval is the default ~11s). It ran for 40 odd minutes and then failed in between. When I try to restart from the UI, it is never able to restore from the last saved checkpoint. I'm guessing it's trying to restore from a checkpoint that was taken 1 hour back (when the current file being written, was opened), which has been cleaned up long back. Since it does not exist now, the job gets stuck there, unable to restore from this non existing checkpoint.

I tried reducing `rollover_seconds` to 5 mins (300s) and increased checkpoint interval to 70s hoping that even if the pipeline fails & tries to restore from a checkpoint, the last file opened would be of 300s earlier and that would be within the last 5 checkpoints (300s < 70s * 5) so it should work. While this worked and the pipeline ran for 19 hrs straight, it faced the above same issue again randomly. Since then, I've not been able to restart the pipeline. The only fix has been tweaking the `rollover_seconds` and checkpoint interval to keep it running or creating the pipeline afresh.

Attaching logs for one such case -
Pipeline was running fine till 5:32 and then encountered an error (worker failed, possibly due to spot node rotation). Last successful checkpoint was 708 and arroyo tried to restore from it.

Controller logs:
<img width="1396" alt="image" src="https://github.com/user-attachments/assets/78c37875-4c56-447f-9aa8-8374d899759b">

But, after the new worker pod came up, it tried to restore from checkpoint 708 and was unable to load it.
Worker logs:
<img width="1396" alt="image" src="https://github.com/user-attachments/assets/0e350c1b-d3e4-496a-847a-c6b09fd5d9b8">

We are using EFS to store checkpoints. When I see the checkpoint 708 there, I can see the different directories (corresponding to the operators in my pipeline), each of them having one metadata file.

_Edit:_ We are also seeing this issue with Kafka to Kafka pipelines so my  hunch is there's some issue with checkpointing and the checkpoints are not being done properly or corrupt, etc. These incomplete/corrupt checkpoints being used by the pipelines for restart is causing the failure issue.

**Comment by mwylde** [comment]
Thanks for reporting. Arroyo wasn't designed to be used with EFS (or shared storage in general), so that may be part of the problem. Would it be possible to test with S3 (or another object store) as the state backend and see if these problems persist?

**Comment by prakkashm** [comment]
Yes, I'm testing it with S3. We switched to EFS on v0.10.1 as we saw checkpoint deletion issue with S3 back then. Arroyo was failing to delete older checkpoints and this operation was failing.

**Comment by prakkashm** [comment]
Checkpointing is working fine with S3, as intended. Thanks for the help!

**Comment by mwylde** [comment]
Thanks for reporting back, and glad it's working!
